version: '3.8'
services:
  spaceapi:
    build: .
    image: odw-spaceapi:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./api.json:/app/api.json:rw
    environment:
      - API_TOKEN=${API_TOKEN:-}
      - PORT=5000
